### ISSUE TITLE
Failure to load brand stores that include other brand stores

### ISSUE THREAD

**Issue by alexclewontin** [canonical/snapcraft.io#4314]
### Expected behaviour

A list of snaps in the brand store.

### Steps to reproduce the problem

Go to https://snapcraft.io/admin. Click on a store which does not include another store. The list of snaps will load properly. Then click on a store which *does* include another store. The screen turns just white.

```
instrument.js:108 TypeError: Cannot read properties of undefined (reading 'includes')
    at Snaps.tsx:250:20
    at Array.filter (<anonymous>)
    at Snaps.tsx:249:24
    at Array.map (<anonymous>)
    at Snaps.tsx:245:21
    at ol (react-dom.production.min.js:244:332)
    at Eu (react-dom.production.min.js:286:111)
    at react-dom.production.min.js:282:391
    at S (scheduler.production.min.js:13:203)
    at MessagePort.N (scheduler.production.min.js:14:128)

Snaps.tsx:250 Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at Snaps.tsx:250:20
    at Array.filter (<anonymous>)
    at Snaps.tsx:249:24
    at Array.map (<anonymous>)
    at Snaps.tsx:245:21
    at ol (react-dom.production.min.js:244:332)
    at Eu (react-dom.production.min.js:286:111)
    at react-dom.production.min.js:282:391
    at S (scheduler.production.min.js:13:203)
    at MessagePort.N (scheduler.production.min.js:14:128)
```

### Specs

- _URL:_ https://snapcraft.io/admin/storeid/snaps, but where storeid is my store's id
- _Operating system:_ Kubuntu 22.04, macOS 12.6
- _Browser:_ Chrome 114.0.5735.198 (on both Kubuntu and macOS), Safari 16.0 (macOS only)

**Comment by steverydz** [comment]
@alexclewontin Thank you for reporting this issue. A fix has been deployed to production.

**Comment by mboudr35** [comment]
Hi,

I seem to be running into a similar issue with "superset" brand stores not loading.

Errors I've extracted appear somewhat different:

Firefox 115.0:

```
instrument.js:108:32
TypeError: t["other-stores"] is undefined
    snaps index.js:268
    Xs index.js:268
    Xs index.js:271
    React 3
    S breadcrumbs.js:82
    R breadcrumbs.js:179
    53 breadcrumbs.js:203
    o trycatch.js:46
    3840 client.js:79
    o trycatch.js:46
    4448 React
    o trycatch.js:46
    3935 React
    o trycatch.js:46
    745 React
    o trycatch.js:46
    <anonymous> trycatch.js:177
    <anonymous> brand-store.tsx:21
    <anonymous> brand-store.tsx:21
    d instrument.js:108
    2]</e/a[b raven.min.js:2
    React 12
    S breadcrumbs.js:82
    R breadcrumbs.js:179
    (Async: EventHandlerNonNull)
    53 breadcrumbs.js:203
    o trycatch.js:46
    3840 client.js:79
    o trycatch.js:46
    4448 React
    o trycatch.js:46
    3935 React
    o trycatch.js:46
    745 React
    o trycatch.js:46
    <anonymous> trycatch.js:177
    <anonymous> brand-store.tsx:21
    <anonymous> brand-store.tsx:21
```

```
index.js:268:31
Uncaught TypeError: t["other-stores"] is undefined
    snaps index.js:268
    Xs index.js:268
    Xs index.js:271
    React 3
    S breadcrumbs.js:82
    R breadcrumbs.js:179
    53 breadcrumbs.js:203
    o trycatch.js:46
    3840 client.js:79
    o trycatch.js:46
    4448 React
    o trycatch.js:46
    3935 React
    o trycatch.js:46
    745 React
    o trycatch.js:46
    <anonymous> trycatch.js:177
    <anonymous> brand-store.tsx:21
    <anonymous> brand-store.tsx:21
    snaps index.js:268
    filter self-hosted:241
    Xs index.js:268
    map self-hosted:221
    Xs index.js:271
    React 3
    S breadcrumbs.js:82
    R breadcrumbs.js:179
    (Async: EventHandlerNonNull)
    53 breadcrumbs.js:203
    o trycatch.js:46
    3840 client.js:79
    o trycatch.js:46
    4448 React
    o trycatch.js:46
    3935 React
    o trycatch.js:46
    745 React
    o trycatch.js:46
    <anonymous> trycatch.js:177
    <anonymous> brand-store.tsx:21
    <anonymous> brand-store.tsx:21
```

Chrome 114.0.5735.198:

```
instrument.js:108
TypeError: Cannot read properties of undefined (reading 'includes')
    at index.js:278:6
    at Array.filter (<anonymous>)
    at index.js:268:13
    at Array.map (<anonymous>)
    at index.js:271:13
    at ou (react-dom.production.min.js:244:332)
    at El (react-dom.production.min.js:286:111)
    at react-dom.production.min.js:282:391
    at S (breadcrumbs.js:82:11)
    at MessagePort.R (breadcrumbs.js:179:23)
(anonymous)	@	instrument.js:108
a.<computed>	@	raven.min.js?v=daf037c:2
fs	@	react-dom.production.min.js:189
n.callback	@	react-dom.production.min.js:189
Ui	@	react-dom.production.min.js:144
wu	@	react-dom.production.min.js:262
_u	@	react-dom.production.min.js:260
bu	@	react-dom.production.min.js:259
(anonymous)	@	react-dom.production.min.js:283
Sl	@	react-dom.production.min.js:281
ll	@	react-dom.production.min.js:273
Vo	@	react-dom.production.min.js:127
El	@	react-dom.production.min.js:286
(anonymous)	@	react-dom.production.min.js:282
S	@	breadcrumbs.js:82
R	@	breadcrumbs.js:179
```

```
index.js:278
Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at index.js:278:6
    at Array.filter (<anonymous>)
    at index.js:268:13
    at Array.map (<anonymous>)
    at index.js:271:13
    at ou (react-dom.production.min.js:244:332)
    at El (react-dom.production.min.js:286:111)
    at react-dom.production.min.js:282:391
    at S (breadcrumbs.js:82:11)
    at MessagePort.R (breadcrumbs.js:179:23)
(anonymous)	@	index.js:278
(anonymous)	@	index.js:268
(anonymous)	@	index.js:271
ou	@	react-dom.production.min.js:244
El	@	react-dom.production.min.js:286
(anonymous)	@	react-dom.production.min.js:282
S	@	breadcrumbs.js:82
R	@	breadcrumbs.js:179
```

**Comment by steverydz** [comment]
@mboudr35 Can you verify if this demo fixes the bug? https://snapcraft-io-4319.demos.haus/admin

**Comment by mboudr35** [comment]
Yes, that seems much better!
